# Description: A simple playbook that prints "Hello, World!" to the console.
- name: Say Hello
  hosts: localhost
  connection: local
  tasks:
    - name: Print Hello World
      debug:
        msg: "Hello, World!"
